"use client";
import { useState, useEffect } from 'react';
import type { Profile, Place } from '@/lib/api';
import { Modal, Ticket } from '@/components/ui';
import { ArrowUpRight, Backpack, CalendarCheck, Check, Compass, ForkKnife, MapPin, Translate } from '@phosphor-icons/react';

export function PlaceCard({place}:{place:Place}) {return <Ticket><h4>{place.display_name}</h4><p>{place.description}</p>{place.cuisine&&<p>{place.cuisine} · {place.signature_dishes}</p>}<p>{place.hours_note}</p><p>{place.ticket_note}</p><p>{place.reservation_note}</p>{place.entity_kind==='experience_concept'&&place.booking_status==='unverified'&&<p className="guide-muted">体验构想，尚未关联可核验地点或预约产品。</p>}<div className="sight-links">{place.map_url&&<a href={place.map_url} target="_blank" rel="noopener noreferrer">地图查看 <ArrowUpRight/></a>}{place.official_url&&<> · <a href={place.official_url} target="_blank" rel="noopener noreferrer">官方网站 <ArrowUpRight/></a></>}</div></Ticket>;}
export function ProfileSight({place,onClose}:{place:Place;onClose:()=>void}){return <Modal open wide title="景点手记" onClose={onClose}><article className="sight-detail"><div className="sight-cover"><MapPin size={60}/><span>{place.city} · 旅途一站</span></div><h2>{place.display_name}</h2><p className="sight-intro">{place.description}</p><div className="guide-note"><b>开放与预约</b><p>{place.hours_note}</p><p>{place.reservation_note}</p><p>{place.ticket_note}</p></div><footer className="sight-links">{place.map_url?<a href={place.map_url} target="_blank" rel="noopener noreferrer">在高德地图查看 <ArrowUpRight size={17}/></a>:<p className="guide-muted">尚未关联可核验地点，暂无地图入口。</p>}{place.official_url?<><span> · </span><a href={place.official_url} target="_blank" rel="noopener noreferrer">官方网站 <ArrowUpRight size={17}/></a></>:<p className="guide-muted">官网尚未确认，出发前请复核。</p>}</footer></article></Modal>;}

export function ProfileWidgets({profile:p}:{profile:Profile}){
 const [view,setView]=useState<'experiences'|'food'|null>(null);const f=p.module_groups.food;
 const cards=(refs:{place_id:string}[])=>refs.map(r=>p.places.find(x=>x.id===r.place_id)).filter((x):x is Place=>Boolean(x)).map(x=><PlaceCard key={x.id} place={x}/>);
 return <><div className="local-guide-widgets">{([{key:'experiences',title:'当地特色体验',text:'把目的地的独特，写进旅行',icon:Compass},{key:'food',title:'餐饮指南',text:'街巷里的地方风味',icon:ForkKnife}] as const).map(({key,title,text,icon:Icon})=><button key={key} onClick={()=>setView(key)}><Icon size={29} weight="duotone"/><span><b>{title}</b><small>{text}</small></span><ArrowUpRight size={18}/></button>)}</div>{view&&<Modal open wide title={view==='food'?'餐饮指南':'当地特色体验'} onClose={()=>setView(null)}><div className="guide-collection">{p.enrichment?.practical==='deferred'&&<p className="guide-muted">部分餐饮与行前补充内容生成超时，核心行程已保存，可稍后继续生成。</p>}{view==='experiences'?p.module_groups.experiences.map(g=><section key={g.title}><h3>{g.title}</h3><div className="guide-note-grid">{cards(g.items)}</div></section>):<><section><h3>{f.menu_guide.title}</h3><p>{f.menu_guide.intro}</p><div className="guide-note-grid">{f.menu_guide.cards.map(n=><Ticket key={n.title}><h4>{n.title}</h4><p>{n.note}</p></Ticket>)}</div><details className="guide-fold"><summary>菜单用语</summary><div className="guide-note-grid">{f.menu_guide.dictionary.map(x=><div key={x.term}><h4>{x.term}</h4><p>{x.meaning}</p><p>{x.ordering_note}</p></div>)}</div></details></section><section><h3>当地小吃</h3><div className="guide-note-grid">{f.local_snacks.map(x=><Ticket key={x.name}><h4>{x.name}</h4><p>{x.description}</p><p>{x.where_to_find}</p><p>{x.ordering_note}</p></Ticket>)}</div></section><section><h3>值得专程品尝</h3><div className="guide-note-grid">{cards(f.dedicated_trip)}</div></section><section><h3>连锁备选</h3><div className="guide-note-grid">{cards(f.reliable_chains)}</div></section></>}<small>营业、预约与费用出发前请复核。</small></div></Modal>}</>;
}

const tabs=[{id:'packing',title:'必备物品',icon:Backpack},{id:'booking',title:'需要预约和确认',icon:CalendarCheck},{id:'language',title:'语言随行锦囊',icon:Translate},{id:'tips',title:'旅游贴士',icon:Compass}] as const;
export function ProfilePreparation({profile:p}:{profile:Profile}){
 const [tab,setTab]=useState<string>('packing');const [checked,setChecked]=useState<string[]>([]);const [ready,setReady]=useState(false);const key=`journey-preparation:${p.id}`;
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(key)??'[]');setChecked(Array.isArray(v)?v.filter(x=>typeof x==='string'):[]);}catch{}setReady(true);},[key]);
 const toggle=(id:string)=>{const next=checked.includes(id)?checked.filter(x=>x!==id):[...checked,id];setChecked(next);try{localStorage.setItem(key,JSON.stringify(next));}catch{}};
 const m=p.module_groups;const items=tab==='packing'?m.preparation.essentials:m.preparation.confirm_ahead;const checklist=tab==='packing'||tab==='booking';
 const deferred=(checklist&&p.enrichment?.practical==='deferred')||(!checklist&&p.enrichment?.language_notes==='deferred');
 return <div className="preparation-layout"><nav className="preparation-menu" aria-label="行前准备栏目">{tabs.map(({id,title,icon:Icon},i)=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><small>0{i+1}</small><Icon size={21} weight="duotone"/><span>{title}</span></button>)}<p>出发前，翻一翻<br/>把安心装进行囊。</p></nav><section className="preparation-content" aria-label={tabs.find(x=>x.id===tab)?.title}><header className="guide-section-heading"><div><span className="guide-eyebrow">旅途备忘录 / 0{tabs.findIndex(x=>x.id===tab)+1}</span><h2>{tabs.find(x=>x.id===tab)?.title}</h2></div>{checklist&&<span>{items.filter(x=>checked.includes(x.id)).length} / {items.length} 已完成</span>}</header>{deferred&&<p className="guide-muted">本区补充内容生成超时，核心行程已保存，可稍后继续生成。</p>}{checklist?<><p className="guide-muted">勾选只记录本机确认进度，不会自动预约或购票。出发前请复核。</p><div className="prep-grid">{items.map(x=><Ticket className="prep-card" key={x.id}><div><label className={checked.includes(x.id)?'checked':''}><input type="checkbox" disabled={!ready} checked={checked.includes(x.id)} onChange={()=>toggle(x.id)}/><span>{checked.includes(x.id)&&<Check size={14}/>}</span>{x.title}</label><p className="guide-muted">{x.note}</p></div></Ticket>)}</div></>:tab==='language'?<><p className="guide-muted">{m.language.edition}</p>{[...m.language.keyword_groups.map(x=>({...x,family:'关键词'})),...m.language.phrase_groups.map(x=>({...x,family:'短语'}))].map(g=><details className="guide-fold" key={g.family+g.title}><summary>{g.family} · {g.title}<span>{g.items.length} 条</span></summary><div className="guide-note-grid">{g.items.map(x=><div key={x.text}><h3>{x.text}</h3><p>{x.pronunciation} {x.meaning}</p></div>)}</div></details>)}</>:m.travel_notes.map(g=><details className="guide-fold" key={g.category} open><summary>{g.title}</summary><p>{g.summary}</p><div className="guide-note-grid">{g.items.map(x=><div key={x.title}><h3>{x.title}</h3><p>{x.note}</p></div>)}</div></details>)}</section></div>;
}
